- src/components/AccountDetail/AccountDetail.tsx
- src/components/AccountDetail/AccountLayout.stories.tsx
- src/components/AccountDetail/AccountLayout.tsx
- src/components/AccountDetail/AccountTitle.tsx
- src/components/AccountDetail/Balance.tsx
- src/components/CommonHeader/CommonHeader.stories.tsx
- src/components/CommonHeader/CommonHeader.tsx
- src/components/CommonHeader/Networks/Networks.stories.tsx
- src/components/CommonHeader/Networks/Networks.tsx
- src/components/CommonHeader/Networks/index.tsx
- src/components/CommonHeader/index.tsx
- src/config/routes.ts
- src/storybookUtils.tsx
- src/styles/logo.tsx
- src/wallet-core/antenna-account.ts
- src/wallet-core/wallet-core.ts
- Description:
- interfaces for balance & activities
- account & network UI
- Fixes #5
> Account detail

- src/components/CreatePassword/CreatePasswordForm.tsx
- Description: improve create password screen exp
- Fixes #17 (Except the loading preloader circle looks strange)
> improve create password screen exp

- src/components/AccountDetail/AccountLayout.tsx
- src/components/AccountDetail/Balance.tsx
- src/components/CommonHeader/CommonHeader.tsx
- src/components/CreatePassword/CreatePasswordForm.tsx
- src/components/Greetings/Welcome.tsx
- src/styles/antd.less
- Description:  improve account detail screen, and add button as `history.goBack() for create password screen`
- Fixes #18
> chore: improve account screen exp

- src/components/CreatePassword/CreatePasswordForm.tsx
- src/components/MyAccounts/MyAccounts.tsx
- src/components/TransferToken/AddRecipient.tsx
- src/components/TransferToken/Amount.tsx
- src/components/TransferToken/AssetSelect.tsx
- src/components/TransferToken/TransactionFee.tsx
- src/components/TransferToken/TransferTokenForm.tsx
- src/components/Unlock/Unlock.tsx
- src/components/Unlock/UnlockForm.tsx
- src/daemon/wallet.ts
- src/styles/logo.tsx
- src/wallet-core/wallet-core.ts
- Description: _what does this PR do?_
- Fixes #25
> feature: unlock and lock ui screen

- src/components/AccountDetail/AccountLayout.tsx
- src/components/AccountDetail/AccountTitle.tsx
- src/components/CreatePassword/CreatePassword.tsx
- src/components/CreatePassword/CreatePasswordForm.stories.tsx
- src/components/TransferToken/AmountInput.tsx
- src/components/TransferToken/RecipienInput.tsx
- src/components/TransferToken/TransactionFeeInput.tsx
- src/components/TransferToken/TransferTokenForm.tsx
- src/components/TransferToken/index.tsx
- src/components/Unlock/Unlock.tsx
- src/components/router.tsx
- src/config/routes.ts
- src/daemon/client.ts
- src/pages/Popup/index.tsx
- src/pages/Popup/state-observer.ts
- src/recoil/selector/index.ts
- Description: improve transfer token screen, and use Memery Router instead of Browser Router
> improve transfer token ui

- src/components/AccountDetail/Balance.tsx
- src/components/AccountDetail/hooks/useAccountMeta.tsx
- src/components/CommonHeader/CommonHeader.tsx
- src/components/CreatePassword/CreatePassword.tsx
- src/components/MyAccounts/AccountItem.tsx
- src/components/MyAccounts/MenuItem.tsx
- src/components/MyAccounts/MyAccounts.tsx
- src/components/Unlock/Unlock.tsx
- src/daemon/client.ts
- src/daemon/wallet.ts
- src/hooks/use-account.ts
- src/hooks/use-network.ts
- src/recoil/atom/index.ts
- src/wallet-core/__test__/wallet-core.test.ts
- src/wallet-core/index.ts
- src/wallet-core/wallet-core.ts
- Description: 
update use-account custom hooks
account ui fix
multi accounts
- Fixes #38 #22
> update account state custom hooks and account ui

- src/components/AccountDetail/Balance.tsx
- src/components/TransferToken/index.tsx
- src/daemon/client.ts
- src/daemon/wallet.ts
- src/wallet-core/antenna-account.ts
- src/wallet-core/wallet-core.ts
- Description: fulfil token transfer process
- Fixes #35
> fulfil token transfer process

- src/components/CommonHeader/CommonHeader.stories.tsx
- src/components/CommonHeader/CommonHeader.tsx
- src/components/CommonHeader/Networks/Networks.stories.tsx
- src/components/CommonHeader/Networks/Networks.tsx
- src/components/CommonHeader/Networks/index.tsx
- src/components/CommonHeader/index.tsx
- src/components/MyAccounts/MyAccounts.stories.tsx
- src/components/MyAccounts/MyAccounts.tsx
- src/components/MyAccounts/index.tsx
- src/components/TransferToken/index.tsx
- src/config/networks.ts
- src/hooks/account.ts
- src/hooks/index.ts
- src/recoil/account.ts
fix broken storybooks and refresh account meta data  when token transcation finished
- Description: fix broken storybooks and refresh account meta data  when token transcation finished
- Fixes #50
> fix broken storybooks and refresh account meta data  when token transcation finished

- src/components/MyAccounts/MyAccounts.tsx
- src/components/MyAccounts/index.tsx
- src/daemon/agent.ts
- src/daemon/index.ts
- Description: delay lock wallet when popup exit
- Fixes #53
> feature: delay lock wallet when popup exit

- src/components/ActionsHistory/index.tsx
- src/daemon/client.ts
- src/daemon/wallet.ts
- src/recoil/account.ts
- src/wallet-core/antenna-account.ts
- src/wallet-core/wallet-core.ts
- Description: display lastest 10 activities in activity list
- Fixes #57
> feat: display lastest 10 activities in activity list

- src/components/AccountDetail/Balance.tsx
- src/components/Greetings/Welcome.tsx
- src/components/ImportKey/ImportKey.tsx
- src/components/ImportKey/ImportKeyForm.stories.tsx
- src/components/ImportKey/ImportKeyForm.tsx
- src/components/ImportKey/index.tsx
- src/config/routes.ts
- src/daemon/client.ts
- src/daemon/wallet.ts
- src/wallet-core/wallet-core.ts
- Description: create account by private key
- Fixes #45
> create account by private key

- src/components/ImportAccount/ImportAccount.stories.tsx
- src/components/ImportAccount/ImportAccount.tsx
- src/components/ImportAccount/ImportAccountForm.tsx
- src/components/ImportAccount/index.ts
- src/components/MyAccounts/MenuItem.tsx
- src/components/MyAccounts/MyAccounts.tsx
- src/components/MyAccounts/index.tsx
- src/config/routes.ts
- src/daemon/client.ts
- src/daemon/wallet.ts
- src/wallet-core/wallet-core.ts
- Description: import account by private key
- Fixes #61
> feat: import account by private key

- src/components/AccountDetail/AccountLayout.tsx
- src/components/ActionsHistory/ActionItem.stories.tsx
- src/components/ActionsHistory/ActionItem.tsx
- src/components/ActionsHistory/ActionsHistory.stories.tsx
- src/components/ActionsHistory/ActionsHistory.tsx
- src/components/ActionsHistory/index.tsx
- src/components/ActivityDetail/ActivityDetail.tsx
- src/components/ActivityDetail/ActivityDetailView.stories.tsx
- src/components/ActivityDetail/ActivityDetailView.tsx
- src/components/ActivityDetail/index.tsx
- src/components/CreatePassword/CreatePasswordForm.tsx
- src/components/ImportAccount/ImportAccount.tsx
- src/components/ImportAccount/ImportAccountForm.tsx
- src/config/routes.ts
- src/daemon/client.ts
- src/daemon/wallet.ts
- src/recoil/index.ts
- src/recoil/others.ts
- src/wallet-core/antenna-account.ts
- src/wallet-core/wallet-core.ts
- Description:  link activity item detail to iotexscan
- Fixes #58
> feat:impl activity detail page

- package.json
- src/components/AccountDetail/AccountTitle.tsx
- Description: account detail address can copy to clipboard
- Fixes #68
> feature: account detail address can copy to clipboard

- package.json
- src/components/MyAccounts/MyAccounts.stories.tsx
- src/components/MyAccounts/MyAccounts.tsx
- src/storybookUtils.tsx
- Description: Scroll when too many account
- Fixes #69 #70
> Scroll when too many account

- .vscode/settings.json
- src/components/AccountDetail/AccountTitle.tsx
- src/config/networks.ts
- src/daemon/client.ts
- src/daemon/wallet.ts
- src/wallet-core/wallet-core.ts
- Description: removing account and check on iotexscan
- Fixes #81
> feature: impl remove account

- src/manifest.json
- src/pages/Background/controller.ts
- src/pages/Background/method.ts
- src/pages/InjectedScript/index.ts
- src/pages/InjectedScript/signer/index.ts
- src/wallet-core/wallet-core.ts
- Description:  contentScript inject signer as window.antennaSigner
> Feature signer

- package.json
- src/components/AccountDetail/AccountTitle.tsx
- src/constant/iotex.ts
- src/pages/Background/antenna-signer-engine/index.ts
- src/pages/Background/antenna-signer-engine/method.ts
- src/pages/Background/antenna-signer-engine/middleware.ts
- src/pages/Background/controller.ts
- src/pages/InjectedScript/signer/index.ts
- tsconfig.json
- webpack.config.inject.js
- webpack.config.js
1. remove clipboard.js instead of antd Paragraph
2. opti antenna signer
3. add paths config in tsconfig.json
> opti antenna signer

- package.json
- src/constant/iotex.ts
- src/pages/Background/antenna-controller-engine/middlewares/tx.ts
- src/pages/Popup/pages/ActionsHistory/ActionItem.tsx
- src/pages/Popup/pages/ActionsHistory/ActionsHistory.tsx
- src/pages/Popup/pages/ActivityDetail/ActivityDetail.tsx
- Description: fix action item view
> fix ui: action item view

- package.json
- utils/webserver.js
- webpack.config.js
- Description: opti webpack config
- Fixes #98
> opti webpack config

- src/constant/iotex.ts
- src/pages/Background/antenna-controller-engine/middlewares/account.ts
- src/pages/Popup/pages/Dashboard/Title.tsx
- src/pages/Popup/postman/index.ts
- src/wallet-core/wallet-core.ts
- Description: export private key
- Fixes #97
> export private key

- package.json
- src/constant/iotex.ts
- src/pages/Background/antenna-controller-engine/middlewares/tokens.ts
- src/pages/Background/antenna-controller-engine/middlewares/tx.ts
- src/pages/Popup/pages/ActivityDetail/ActivityDetail.tsx
- src/pages/Popup/pages/ActivityDetail/ActivityDetailView.stories.tsx
- src/pages/Popup/pages/ActivityDetail/ActivityDetailView.tsx
- src/pages/Popup/pages/TransferToken/AssetSelect.tsx
- src/pages/Popup/pages/TransferToken/TransferTokenForm.tsx
- src/pages/Popup/pages/TransferToken/index.tsx
- src/pages/Popup/postman/index.ts
- src/wallet-core/wallet-core.ts
- Description:  support transfer xrc20 token and action detail page add timstamp
- Fixes #112
- Fixes #110
- Fixes #111
> support transfer xrc20 token and action detail page add timstamp
